# Generated by Django 3.2 on 2021-04-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheet1',
            fields=[
                ('time', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('number_126_in', models.IntegerField(blank=True, db_column='126_in', null=True)),
                ('number_126_out', models.IntegerField(blank=True, db_column='126_out', null=True)),
            ],
            options={
                'verbose_name_plural': '126进出情况',
                'db_table': 'sheet1',
            },
        ),
        migrations.CreateModel(
            name='Sheet2',
            fields=[
                ('day_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('weather', models.CharField(blank=True, max_length=255, null=True)),
                ('tmax', models.CharField(blank=True, db_column='Tmax', max_length=255, null=True)),
                ('tmin', models.CharField(blank=True, db_column='Tmin', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': '城市天气数据',
                'db_table': 'sheet2',
            },
        ),
    ]
