# Generated by Django 3.2 on 2021-04-21 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('vegion', models.CharField(blank=True, max_length=255, null=True, verbose_name='行政区域')),
            ],
            options={
                'verbose_name_plural': '站点',
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workdays2020',
            fields=[
                ('date', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'workdays2020',
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('in_name', models.CharField(max_length=255, verbose_name='入站名')),
                ('date_in', models.CharField(max_length=255, verbose_name='入站时间')),
                ('out_name', models.CharField(max_length=255, verbose_name='出站名')),
                ('date_out', models.CharField(max_length=255, verbose_name='出站时间')),
                ('channel_id', models.CharField(max_length=255, verbose_name='渠道类型')),
                ('price', models.CharField(max_length=255, verbose_name='票价')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
            options={
                'verbose_name_plural': '乘车记录',
                'db_table': 'trips',
            },
        ),
    ]
