# Generated by Django 3.1.7 on 2021-03-31 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Errordata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('in_name', models.CharField(blank=True, max_length=255, null=True)),
                ('in_time', models.CharField(blank=True, max_length=255, null=True)),
                ('out_name', models.CharField(blank=True, max_length=255, null=True)),
                ('out_time', models.CharField(blank=True, max_length=255, null=True)),
                ('route_id', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'errordata',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=255)),
                ('route', models.CharField(max_length=255)),
                ('vegion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'station',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=255)),
                ('birth_year', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Workdays2020',
            fields=[
                ('number_20200101', models.CharField(db_column='20200101', max_length=255, primary_key=True, serialize=False)),
                ('number_3', models.CharField(db_column='3', max_length=255)),
            ],
            options={
                'db_table': 'workdays2020',
            },
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_name', models.CharField(max_length=255)),
                ('in_time', models.CharField(max_length=255)),
                ('out_name', models.CharField(max_length=255)),
                ('out_time', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.users')),
            ],
            options={
                'db_table': 'trips',
            },
        ),
    ]
